Fixed recent bug with expanding loopkey of ccdnum when it has (a:b) notation instead of a comma separated list.
Error Message:
    winst[loopkeys[k]] = instvals[k]
IndexError: tuple index out of range